# Generated by Django 2.0.2 on 2018-09-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='provideDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='closeDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='openDateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='table_status',
            name='endDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_status',
            name='reservationDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_status',
            name='startDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
