# Generated by Django 2.0.2 on 2018-09-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MENU',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creation_time', models.IntegerField(default=1)),
                ('orderable_flg', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MENU_TYPE',
            fields=[
                ('menu_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.IntegerField(default=0)),
                ('mail', models.EmailField(default='*@*', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ORDER_DETAIL',
            fields=[
                ('orderDetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_qty', models.IntegerField(default=1)),
                ('supply_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RESERVE_TABLE',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='STORE',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TABLE',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_qty', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='MENU_CROWD',
            fields=[
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fromMenuCrowd_menuId', serialize=False, to='food_court_app.MENU')),
                ('wating_time', models.IntegerField(default=1)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='STORE_CROWD',
            fields=[
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fromStoreCrowd_menuId', serialize=False, to='food_court_app.STORE')),
                ('wating_time', models.IntegerField(default=1)),
                ('crowd_status', models.IntegerField(default=0)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='reserve_table',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromReserveTable_tableId', to='food_court_app.TABLE'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromOrderDetail_menuId', to='food_court_app.MENU'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromOrderDetail_orderId', to='food_court_app.ORDER'),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromOrder_reservationId', to='food_court_app.RESERVE_TABLE'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromMenu_menuTypeId', to='food_court_app.MENU_TYPE'),
        ),
        migrations.AddField(
            model_name='menu',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromMenu_storeId', to='food_court_app.STORE'),
        ),
    ]
