# Generated by Django 2.0.2 on 2018-09-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_court_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='store_image/'),
        ),
    ]
