# Generated by Django 2.0.2 on 2018-09-25 04:01

from django.db import migrations, models
import food_court_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_court_app', '0002_store_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='orderDetail_id',
            new_name='order_detail_id',
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='order_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='image_file',
            field=models.ImageField(upload_to=food_court_app.models.get_image_path),
        ),
    ]
