# Generated by Django 2.0.2 on 2018-09-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AREA',
            fields=[
                ('areaId', models.IntegerField(primary_key=True, serialize=False)),
                ('xCoordinate', models.IntegerField(default=0)),
                ('yCoordinate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MENU',
            fields=[
                ('menuId', models.IntegerField(primary_key=True, serialize=False)),
                ('menuName', models.CharField(max_length=20)),
                ('menuType', models.CharField(default='00000', max_length=5)),
                ('price', models.IntegerField(default=0)),
                ('estTime', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('orderDateTime', models.DateField()),
                ('totalPrice', models.IntegerField(default=0)),
                ('orderStatus', models.CharField(max_length=2)),
                ('mailAddress', models.EmailField(default='*@*', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ORDER_DETAIL',
            fields=[
                ('orderDetailId', models.IntegerField(primary_key=True, serialize=False)),
                ('orderNum', models.IntegerField(default=1)),
                ('orderStatus', models.CharField(max_length=2)),
                ('provideDateTime', models.DateField(blank=True, null=True)),
                ('cancelFlg', models.BooleanField(default=False)),
                ('menuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromOrderDetail_menuId', to='manageTable.MENU')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromOrderDetail_orderId', to='manageTable.ORDER')),
            ],
        ),
        migrations.CreateModel(
            name='SHOP',
            fields=[
                ('shopId', models.IntegerField(primary_key=True, serialize=False)),
                ('shopName', models.CharField(max_length=50)),
                ('openDateTime', models.DateField()),
                ('closeDateTime', models.DateField(blank=True, null=True)),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromShop_areaId', to='manageTable.AREA')),
            ],
        ),
        migrations.CreateModel(
            name='TABLE',
            fields=[
                ('tableId', models.IntegerField(primary_key=True, serialize=False)),
                ('seatsNum', models.IntegerField(default=4)),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromTable_areaId', to='manageTable.AREA')),
            ],
        ),
        migrations.CreateModel(
            name='TABLE_STATUS',
            fields=[
                ('reservationId', models.IntegerField(primary_key=True, serialize=False)),
                ('reservationDateTime', models.DateField(blank=True, null=True)),
                ('startDateTime', models.DateField(blank=True, null=True)),
                ('endDateTime', models.DateField(blank=True, null=True)),
                ('cancelFlg', models.BooleanField(default=False)),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromTabaleStatus_tableId', to='manageTable.TABLE')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='reservationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromOrder_reservationId', to='manageTable.TABLE_STATUS'),
        ),
        migrations.AddField(
            model_name='menu',
            name='shopId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromMenu_shopId', to='manageTable.SHOP'),
        ),
    ]
