# Generated by Django 2.0.2 on 2018-09-11 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MENU',
            fields=[
                ('menuId', models.AutoField(primary_key=True, serialize=False)),
                ('menuName', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creationTime', models.IntegerField(default=1)),
                ('orderableFlg', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MENU_TYPE',
            fields=[
                ('menuTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('menuTypeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.IntegerField(default=0)),
                ('mail', models.EmailField(default='*@*', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ORDER_DETAIL',
            fields=[
                ('orderDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('orderQty', models.IntegerField(default=1)),
                ('supplyTime', models.DateTimeField(blank=True, null=True)),
                ('cancelFlg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RESERVE_TABLE',
            fields=[
                ('reservationId', models.AutoField(primary_key=True, serialize=False)),
                ('reservationTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('cancelFlg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='STORE',
            fields=[
                ('storeId', models.AutoField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=50)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TABLE',
            fields=[
                ('tableId', models.AutoField(primary_key=True, serialize=False)),
                ('seaqty', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='MENU_CROWD',
            fields=[
                ('menuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fromMenuCrowd_menuId', serialize=False, to='manageTable.MENU')),
                ('watingTime', models.IntegerField(default=1)),
                ('modifiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='STORE_CROWD',
            fields=[
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fromStoreCrowd_menuId', serialize=False, to='manageTable.STORE')),
                ('watingTime', models.IntegerField(default=1)),
                ('crowdStatus', models.IntegerField(default=0)),
                ('modifiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='reserve_table',
            name='tableId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromReserveTable_tableId', to='manageTable.TABLE'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='menuId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromOrderDetail_menuId', to='manageTable.MENU'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromOrderDetail_orderId', to='manageTable.ORDER'),
        ),
        migrations.AddField(
            model_name='order',
            name='reservationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromOrder_reservationId', to='manageTable.RESERVE_TABLE'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menuTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromMenu_menuTypeId', to='manageTable.MENU_TYPE'),
        ),
        migrations.AddField(
            model_name='menu',
            name='storeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromMenu_storeId', to='manageTable.STORE'),
        ),
    ]
